{
  "formatVersion": "1.1",
  "component": {
    "group": "com.flutterchat.module",
    "module": "flutter_release",
    "version": "1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-f6344b75dcf861d8bf1f1322780b8811f982e31a"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-f6344b75dcf861d8bf1f1322780b8811f982e31a"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-f6344b75dcf861d8bf1f1322780b8811f982e31a"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-f6344b75dcf861d8bf1f1322780b8811f982e31a"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.aar",
          "url": "flutter_release-1.aar",
          "size": 5412447,
          "sha512": "3074c56a430c7969b23a2eabe56cbd194b10235182b93885357032f36ff6902adba4e83d57ded772d359d842c10d7e0acf35f8eac4741d57df30c26c71210d70",
          "sha256": "cd7e9ca46d3d9e992d5dab9f04111444cd2a87c2e25c0c28e565b9a4d40027ba",
          "sha1": "f394b9f0c69485edfe7832d1a9235cf50518dd24",
          "md5": "7d915d2fc4cd7334868db8c9889ffaf2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-f6344b75dcf861d8bf1f1322780b8811f982e31a"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-f6344b75dcf861d8bf1f1322780b8811f982e31a"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-f6344b75dcf861d8bf1f1322780b8811f982e31a"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-f6344b75dcf861d8bf1f1322780b8811f982e31a"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.aar",
          "url": "flutter_release-1.aar",
          "size": 5412447,
          "sha512": "3074c56a430c7969b23a2eabe56cbd194b10235182b93885357032f36ff6902adba4e83d57ded772d359d842c10d7e0acf35f8eac4741d57df30c26c71210d70",
          "sha256": "cd7e9ca46d3d9e992d5dab9f04111444cd2a87c2e25c0c28e565b9a4d40027ba",
          "sha1": "f394b9f0c69485edfe7832d1a9235cf50518dd24",
          "md5": "7d915d2fc4cd7334868db8c9889ffaf2"
        }
      ]
    }
  ]
}
