{
  "formatVersion": "1.1",
  "component": {
    "group": "com.flutterchat.module",
    "module": "flutter_release",
    "version": "1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-f6344b75dcf861d8bf1f1322780b8811f982e31a"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-f6344b75dcf861d8bf1f1322780b8811f982e31a"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-f6344b75dcf861d8bf1f1322780b8811f982e31a"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-f6344b75dcf861d8bf1f1322780b8811f982e31a"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.aar",
          "url": "flutter_release-1.aar",
          "size": 5412624,
          "sha512": "13ab74418ea6e8122f57a5c5d21fd5bc891acd120447d50f76a828a04b94996ec5311f722c240ff3267ce6dc31dd7c384b700cf68ecf999fe5de6b2870eeda2e",
          "sha256": "04d799233fee906b4788de34092dd3688f89354411e01c72719bf468c7dc6466",
          "sha1": "4a9d8adae30c4213d46a07870dbaa3bd6976fab2",
          "md5": "5a458c45a111c6800deb5418a37e73d2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-f6344b75dcf861d8bf1f1322780b8811f982e31a"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-f6344b75dcf861d8bf1f1322780b8811f982e31a"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-f6344b75dcf861d8bf1f1322780b8811f982e31a"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-f6344b75dcf861d8bf1f1322780b8811f982e31a"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.aar",
          "url": "flutter_release-1.aar",
          "size": 5412624,
          "sha512": "13ab74418ea6e8122f57a5c5d21fd5bc891acd120447d50f76a828a04b94996ec5311f722c240ff3267ce6dc31dd7c384b700cf68ecf999fe5de6b2870eeda2e",
          "sha256": "04d799233fee906b4788de34092dd3688f89354411e01c72719bf468c7dc6466",
          "sha1": "4a9d8adae30c4213d46a07870dbaa3bd6976fab2",
          "md5": "5a458c45a111c6800deb5418a37e73d2"
        }
      ]
    }
  ]
}
