{
  "formatVersion": "1.1",
  "component": {
    "group": "com.flutterchat.module",
    "module": "flutter_release",
    "version": "1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-f6344b75dcf861d8bf1f1322780b8811f982e31a"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-f6344b75dcf861d8bf1f1322780b8811f982e31a"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-f6344b75dcf861d8bf1f1322780b8811f982e31a"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-f6344b75dcf861d8bf1f1322780b8811f982e31a"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.aar",
          "url": "flutter_release-1.aar",
          "size": 5412733,
          "sha512": "49a31908f61e2ac1d30d47d6bc6e6eea33831a909ae124513f081ee64b32a5ef579e8c29eeb4331f245d7af63f2ab65586e8e5819d45f7c3746d0d2db548b952",
          "sha256": "fc0cb0d5819d525436097273fc53826c8c489bd47f1a73adf852a268d34b672c",
          "sha1": "4b9928ff988d19b5752eb36348c11b0fd5838d00",
          "md5": "9a9604b7b46636275c07b000f7f7830e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-f6344b75dcf861d8bf1f1322780b8811f982e31a"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-f6344b75dcf861d8bf1f1322780b8811f982e31a"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-f6344b75dcf861d8bf1f1322780b8811f982e31a"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-f6344b75dcf861d8bf1f1322780b8811f982e31a"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.aar",
          "url": "flutter_release-1.aar",
          "size": 5412733,
          "sha512": "49a31908f61e2ac1d30d47d6bc6e6eea33831a909ae124513f081ee64b32a5ef579e8c29eeb4331f245d7af63f2ab65586e8e5819d45f7c3746d0d2db548b952",
          "sha256": "fc0cb0d5819d525436097273fc53826c8c489bd47f1a73adf852a268d34b672c",
          "sha1": "4b9928ff988d19b5752eb36348c11b0fd5838d00",
          "md5": "9a9604b7b46636275c07b000f7f7830e"
        }
      ]
    }
  ]
}
